### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by viniciussoaresti** [viniciussoaresti/pantrie#20]
The system should have continous integration, done with TravisCI.

**Comment by viniciussoaresti** [comment]
https://levelup.gitconnected.com/angular-6-travis-ci-with-headless-chrome-58fab1b394e1

**Comment by viniciussoaresti** [comment]
Travisci log:
[karma] No captured browser, open http://localhost:9876/

**Comment by fabriciofx** [comment]
@viniciussoaresti please, paste the travisci's log error here.

**Comment by viniciussoaresti** [comment]
@fabriciofx let me just try something I've just found

**Comment by viniciussoaresti** [comment]
https://angular.io/guide/testing#configure-project-for-travis-ci

**Comment by viniciussoaresti** [comment]
Changed yml travis file, returned:
[16:24:29] E/configParser - Error code: 105
[16:24:29] E/configParser - Error message: failed loading configuration file /home/travis/build/viniciussoaresti/pantrie/e2e/protractor-ci.conf.js
[16:24:29] E/configParser - Error: Cannot find module '/home/travis/build/viniciussoaresti/pantrie/e2e/protractor-ci.conf.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at ConfigParser.addFileConfig (/home/travis/build/viniciussoaresti/pantrie/node_modules/protractor/built/configParser.js:135:26)
    at Object.initFn [as init] (/home/travis/build/viniciussoaresti/pantrie/node_modules/protractor/built/launcher.js:93:22)
    at process.on (/home/travis/build/viniciussoaresti/pantrie/node_modules/@angular-devkit/build-angular/src/utils/run-module-worker.js:14:41)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pantrie@0.0.0 e2e: `ng e2e "--protractor-config=e2e/protractor-ci.conf.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR!0m Failed at the pantrie@0.0.0 e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-11-23T16_24_29_374Z-debug.log
The command "npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js" exited with 1.
cache.2
store build cache
Done. Your build exited with 1.

**Comment by viniciussoaresti** [comment]
Googling protractor-ci.conf.js.
The file doesn't really exist, just a similar one: protractor.conf.js

**Comment by viniciussoaresti** [comment]
Thought: maybe the -ci is just for declaring different files for the same purpose. Will test.

**Comment by viniciussoaresti** [comment]
Solved by e1f382398fd0edff6e406d7d523026eff0a40b33.
